---
  openapi: "3.0.0"
  info: 
    title: "Skill matrix service"
    description: "This service defines the main API methods"
    version: "1.0.0"
    contact: 
      name: "Dmitriy Prokhorov"
      email: "dmitriy.prokhorov.04@gmail.com"
  host: "localhost:8080"
  basePath: "/"
  produces: 
    - "application/json"
  schemes: 
    - "http"
  securityDefinitions: 
    JWT: 
      type: "apiKey"
      in: "header"
      name: "Authorization"
      description: ""
  paths: 
    /api/image/upload: 
      post: 
        summary: "Upload an image file"
        description: "Uploads an image, converts it to WEBP, creates a thumbnail, and returns metadata."
        tags: 
          - "Image"
        requestBody: 
          required: true
          content: 
            multipart/form-data: 
              schema: 
                type: "object"
                properties: 
                  image: 
                    type: "string"
                    format: "binary"
        responses: 
          201: 
            description: "Image uploaded successfully"
            content: 
              application/json: 
                schema: 
                  $ref: "#/components/schemas/ImageDTO"
          400: 
            description: "No file uploaded"
          500: 
            description: "Failed to process file or unsupported mime type"
    /api/image/{id}: 
      get: 
        summary: "Get image by ID"
        description: "Returns the image file or its thumbnail by ID."
        tags: 
          - "Image"
        parameters: 
          - 
            in: "path"
            name: "id"
            required: true
            schema: 
              type: "string"
            description: "Image ID"
          - 
            in: "query"
            name: "thumb"
            required: false
            schema: 
              type: "boolean"
            description: "If true, returns thumbnail"
        responses: 
          200: 
            description: "Image file"
            content: 
              image/webp: 
                schema: 
                  type: "string"
                  format: "binary"
          404: 
            description: "File not found"
    /api/jobrole: 
      post: 
        summary: "Create a job role"
        tags: 
          - "JobRole"
        requestBody: 
          required: true
          content: 
            application/json: 
              schema: 
                type: "object"
                properties: 
                  title: 
                    type: "string"
                    description: "Title of the job role"
        responses: 
          201: 
            description: "Job role created"
            content: 
              application/json: 
                schema: 
                  $ref: "#/components/schemas/JobRoleDTO"
    /api/jobrole/{id}: 
      get: 
        summary: "Get job role by ID"
        tags: 
          - "JobRole"
        parameters: 
          - 
            in: "path"
            name: "id"
            required: true
            schema: 
              type: "string"
        responses: 
          200: 
            description: "Job role found"
            content: 
              application/json: 
                schema: 
                  $ref: "#/components/schemas/JobRoleDTO"
          404: 
            description: "Job role not found"
      put: 
        summary: "Update job role"
        tags: 
          - "JobRole"
        parameters: 
          - 
            in: "path"
            name: "id"
            required: true
            schema: 
              type: "string"
        requestBody: 
          required: true
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/JobRoleDTO"
        responses: 
          200: 
            description: "Job role updated"
            content: 
              application/json: 
                schema: 
                  $ref: "#/components/schemas/JobRoleDTO"
          404: 
            description: "Job role not found"
      delete: 
        summary: "Delete job role"
        tags: 
          - "JobRole"
        parameters: 
          - 
            in: "path"
            name: "id"
            required: true
            schema: 
              type: "string"
        responses: 
          204: 
            description: "Job role deleted"
          404: 
            description: "Job role not found"
    /api/jobrole/search: 
      get: 
        summary: "Search job roles"
        tags: 
          - "JobRole"
        parameters: 
          - 
            in: "query"
            name: "query"
            required: true
            schema: 
              type: "string"
        responses: 
          200: 
            description: "List of job roles"
            content: 
              application/json: 
                schema: 
                  type: "array"
                  items: 
                    $ref: "#/components/schemas/JobRoleDTO"
    /api/user: 
      post: 
        summary: "Create a user"
        tags: 
          - "User"
        requestBody: 
          required: true
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/UserDTO"
        responses: 
          201: 
            description: "User created"
            content: 
              application/json: 
                schema: 
                  $ref: "#/components/schemas/UserDTO"
    /api/user/{id}: 
      get: 
        summary: "Get user by ID"
        tags: 
          - "User"
        parameters: 
          - 
            in: "path"
            name: "id"
            required: true
            schema: 
              type: "string"
        responses: 
          200: 
            description: "User found"
            content: 
              application/json: 
                schema: 
                  $ref: "#/components/schemas/UserDTO"
          404: 
            description: "User not found"
      put: 
        summary: "Update user"
        tags: 
          - "User"
        parameters: 
          - 
            in: "path"
            name: "id"
            required: true
            schema: 
              type: "string"
        requestBody: 
          required: true
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/UserDTO"
        responses: 
          200: 
            description: "User updated"
            content: 
              application/json: 
                schema: 
                  $ref: "#/components/schemas/UserDTO"
          404: 
            description: "User not found"
      delete: 
        summary: "Delete user"
        tags: 
          - "User"
        parameters: 
          - 
            in: "path"
            name: "id"
            required: true
            schema: 
              type: "string"
        responses: 
          204: 
            description: "User deleted"
          404: 
            description: "User not found"
    /api/user/search: 
      get: 
        summary: "Search users"
        tags: 
          - "User"
        parameters: 
          - 
            in: "query"
            name: "query"
            required: true
            schema: 
              type: "string"
        responses: 
          200: 
            description: "List of users"
            content: 
              application/json: 
                schema: 
                  type: "array"
                  items: 
                    $ref: "#/components/schemas/UserDTO"
  components: 
    schemas: 
      ImageDTO: 
        type: "object"
        properties: 
          id: 
            type: "string"
            description: "Unique identifier for the image"
          width: 
            type: "integer"
            description: "Width of the image in pixels"
          height: 
            type: "integer"
            description: "Height of the image in pixels"
          mimeType: 
            type: "string"
            description: "MIME type of the image (e.g., image/webp)"
      JobRoleDTO: 
        type: "object"
        properties: 
          id: 
            type: "string"
            description: "Unique identifier for the job role"
          title: 
            type: "string"
            description: "Title of the job role"
      UserDTO: 
        type: "object"
        properties: 
          id: 
            type: "string"
            description: "Unique identifier for the user"
          login: 
            type: "string"
          firstname: 
            type: "string"
          lastname: 
            type: "number"
          patronymic: 
            type: "string"
          avatar_id: 
            type: "string"
          email: 
            type: "string"
  tags: []
