---
  info: 
    title: "Skill matrix service"
    description: "This service defines the main API methods"
    version: "1.0.0"
    contact: 
      name: "Dmitriy Prokhorov"
      email: "dmitriy.prokhorov.04@gmail.com"
  host: "localhost:8080"
  basePath: "/"
  produces: 
    - "application/json"
  schemes: 
    - "http"
  securityDefinitions: 
    JWT: 
      type: "apiKey"
      in: "header"
      name: "Authorization"
      description: ""
  swagger: "2.0"
  paths: {}
  definitions: {}
  responses: {}
  parameters: {}
  tags: []
